export type TopHolder = {
  wallet: string;
  amount: number;
  percentage: number;
  _id: string;
};

export type Token = {
  _id: string;
  version: number;
  token: string;
  tokenType: string;
  supply: number;
  decimals: number;
  mint_time: number;
  name: string;
  symbol: string;
  metadataUri: string;
  photo: string;
  description: string;
  website: string;
  x: string;
  telegram: string;
  creator: string;
  pool: string;
  hardcap: number;
  list_time: number;
  isMigrated: boolean;
  migrationPool: string;
  lastTradeId: string;
  lastTradeExecutionPositionKey: null;
  priceSol: number;
  priceUsd: number;
  marketCapUsd: number;
  progress: number;
  progressSol: number;
  _balanceSol: number;
  _balanceTokens: number;
  last_tx_time: number;
  buys: number;
  sells: number;
  txCount: number;
  holders: number;
  volumeSol: number;
  volumeUsd: number;
  isDraft: boolean;
  configAddress: string;
  createdAt: string;
  updatedAt: string;
  price: number;
  topHoldersPercentage: number;
  topHoldersList: TopHolder[];
  creatorSharePercentage: number;
};

export type TokenUpdate = {
  token: string;
  price: number;
  priceUsd: number;
  volumeSol: number;
  volumeUsd: number;
  buys: number;
  sells: number;
  txCount: number;
  last_tx_time: number;
  marketCapUsd: number;
  progress: number;
  progressSol: number;
  _balanceSol: number;
  _balanceTokens: number;
  lastUpdated: number;
};
